apiVersion: v1
kind: ConfigMap
metadata:
  name: jmx-configs
data:
  conf.yaml: |
    init_config:
    instances:
      - jvm_direct: true
        conf:
          - include:
              domain: Zoo
              bean_regex:
                - Zoo:Kingdom=([^,]+),Genus=([^,]+),name=([^,]+)
              attribute:
                HR:
                  metric_type: gauge
                  alias: zoo.pet.v2.hr
              tags:
                capturing_group_example: $2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmx
  labels:
    app.kubernetes.io/name: jmx
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: jmx
      tags.datadoghq.com/version: "0.1a"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jmx
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/env: sandbox
        tags.datadoghq.com/service: jmx
        tags.datadoghq.com/version: "0.1a"
      annotations:
        admission.datadoghq.com/java-lib.version: latest
    spec:
      initContainers:
        - name: init-copy-war
          image: alpine
          imagePullPolicy: Always
          command: ["sh", "-c", "--"]
          args:
            - |-
              wget -O /var/app/sandbox.jar https://github.com/yafernandes/java-sandbox/releases/download/v0.0.1rc/sandbox.jar
          volumeMounts:
            - mountPath: /var/app
              name: war
      containers:
        - name: jmx
          image: openjdk:8
          command:
            - java
          args:
            - -jar
            - /var/app/sandbox.jar
            - jmx
          env:
            - name: DD_JMXFETCH_CONFIG
              value: /datadog-jmx/conf.yaml
          resources:
            limits: {}
          volumeMounts:
            - mountPath: /var/app
              name: war
            - mountPath: /datadog-jmx
              name: jmx-configs
      volumes:
        - name: war
          emptyDir: {}
        - name: jmx-configs
          configMap:
            name: jmx-configs
